- src/App.vue
- src/helpers.js
- src/router/index.js
- src/store/index.js
- src/store/modules/auth.js
- src/store/modules/authKeep.js
- src/store/store-moderator.js
Check ping status on route changes (or on load page). 
- This doesn't halt page loading unless explicitly mentioned in route meta.
- Removes user info from store if ping response is exactly 401
- Disables storing auth information in localstorage
- Keep token in a new store module
> fix remaining logged_in when actually user is logged_out

- src/components/AuthLogin.vue
- src/components/BaseInputText.vue
- src/components/BaseInputTextarea.vue
- src/components/MemoAddStep1.vue
- src/styles/base.css
- src/styles/tailwind-utilities.js
- src/styles/tailwind.css
- src/views/AuthLogin.vue
- src/views/Home.vue
- tailwind.config.js
- Add temp dashboard and login form
- Minor changes on input/textarea components label backgrounds
- Add some text style classes (h1-mobile, ...) in tailwind utilities.
https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/69 https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/75
> 69 add login page

- src/components/BaseInputText.vue
As discussed here
https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/69#issuecomment-615113464
> fix autofill style of inputtext

- src/store/modules/memo.js
- src/store/store-moderator.js
- src/views/MemoAdd.vue
https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/82
> clear memo - after successful sending and after logout

- src/App.vue
- src/components/StepperFooter.vue
- src/components/StepperHeader.vue
- src/components/StepperManager.vue
- src/mixins/vh-fix.js
> fix: safari full height issue and zindex problem of stepper header/footer

- .vscode/settings.json
- README.md
- package.json
- postcss.config.js
- src/styles/animations.css
- src/styles/elevation.css
- src/styles/tailwind-utilities.js
- src/styles/tailwind.css
- src/styles/typography.css
- stylelint.config.js
- yarn.lock
- Setup text styles and shadows utilities
- Add Stylelint
#17
> Setup text styles and shadows + add stylelint

- src/styles/emphasis.css
- src/styles/tailwind.css
Add emphasis.css:
`<span class="primary em-high">...`
classes: `em-high` `em-medium` `em-disabled` `em-error`
> add emphasis utilities (text opacity)

- src/router/index.js
- src/store/modules/distributionGroup.js
- src/views/EmailListImport.vue
- src/views/Settings.vue
- tailwind.config.js
https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/74
> 74 settings import email list

- package.json
- src/components/ActivityFeedReadReportLog.vue
- src/components/ActivityFeedSearchBox.vue
- src/components/BaseAppBarHeader.vue
- src/components/BaseInputText.vue
- src/components/BaseProgressBar.vue
- src/components/BaseTab.vue
- src/components/BaseTabs.vue
- src/components/LayoutFixedScrollable.vue
- src/components/MemoAddStep1.vue
- src/components/MemoListItem.vue
- src/router/index.js
- src/store/modules/memo.js
- src/styles/tailwind-utilities.js
- src/styles/typography.css
- src/views/ActivityFeedMemoItem.vue
- src/views/ActivityFeedMemoList.vue
- src/views/Settings.vue
- tailwind.config.js
- yarn.lock
https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/76
> 76 add memo tracking

- src/components/BaseAppBarHeader.vue
- src/router/index.js
- src/views/EmailListAdd.vue
- src/views/EmailListImport.vue
- src/views/EmailLists.vue
- src/views/Settings.vue
This address issue [#43](https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/43)
> Fix place of link's Email Lists Import

- src/styles/tailwind.css
- src/views/EmailListAdd.vue
- src/views/EmailListEdit.vue
- tailwind.config.js
This address issues [#45](https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/45)
I fixed an issue on add email, clean input after the destroyed page.
> fix issues on Add Email

- src/views/EmailListItem.vue
This issue [#46](https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/46)
> Fix format date in the email list item page

- src/store/modules/distributionGroup.js
- src/views/EmailListEdit.vue
- src/views/EmailListItem.vue
> Fix edit email, same issue with add email

- src/components/ActivityFeedReadReportLog.vue
- src/components/MemoListItem.vue
- src/components/MemoOpenRateItem.vue
- src/helpers.js
- src/router/index.js
- src/store/modules/memo.js
- src/views/ActivityFeedMemoItem.vue
- src/views/ActivityFeedMemoList.vue
- src/views/MemoAdd.vue
add dynamic data  
make read report functional  
minor styles
https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/77  
https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/76  
_Search is not ready, pending backend_
> activity feed - make data dynamic + minor styling

- public/index.html
https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/80
> 80-Install-GTM

- src/components/BaseInputText.vue
- src/components/BaseTabs.vue
- src/views/ActivityFeedMemoItem.vue
style for desktop, style search input
https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/77
> activity feed - style for desktop, style search input

- src/App.vue
- src/styles/tailwind.css
> Page Transition Animation

- src/components/ActivityFeedReadReportLog.vue
- src/components/MemoListItem.vue
- src/components/MemoOpenRateItem.vue
- src/helpers.js
- src/views/ActivityFeedMemoItem.vue
- src/views/EmailList.vue
- src/views/EmailListItem.vue
- change all date formats to M/d/yyyy
- fix date errors in memo stats 
- style memo stats logs
#59
> 59 fix errors memo stats, change date format everywhere

- src/views/ActivityFeedMemoItem.vue
- src/views/ActivityFeedMemoList.vue
- src/views/EmailCampaign.vue
> hide incomplete features (search and default time)

- src/components/BaseStepperCircle.vue
> No wrap text in stepper circle

- README.md
- package.json
- src/views/AuthLogin.vue
- src/views/Home.vue
> change titles and package name

- src/components/BaseProgressCircle.vue
- src/components/BaseStepperCircle.vue
- fix logo (same fix as Somaye did)
#60
> fix success overlay logo

- public/index.html
> prevent zoom in mobile

- src/styles/plugin-multiselect.css
> Fix hide icon of multiselect

- src/components/MemoListItem.vue
- src/components/MemoOpenRateItem.vue
- src/helpers.js
- src/views/ActivityFeedMemoItem.vue
- src/views/EmailList.vue
> date format - change to dd MM, yyyy

- src/views/EmailLists.vue
> Update Email Lists Page

- src/styles/animations.css
- src/views/ActivityFeedMemoList.vue
- src/views/EmailCampaign.vue
- src/views/EmailList.vue
- src/views/EmailListAdd.vue
- src/views/EmailListEdit.vue
- src/views/EmailListItem.vue
- src/views/EmailLists.vue
- src/views/Home.vue
- src/views/Settings.vue
> #81 fix issue on nav bottom

- netlify.toml
Reverts whynotearth/Volkswagen-email-corporate-communications-CMS#108
> Revert "107 hotfix change api of production"

- src/components/BaseNavigationBottom.vue
- src/views/ActivityFeedMemoItem.vue
- src/views/ActivityFeedMemoList.vue
- src/views/EmailCampaign.vue
- src/views/EmailList.vue
- src/views/EmailListAdd.vue
- src/views/EmailListEdit.vue
- src/views/EmailListImport.vue
- src/views/EmailListImportHelp.vue
- src/views/EmailListItem.vue
- src/views/EmailLists.vue
- src/views/Home.vue
- src/views/Settings.vue
> Fix overlapping bottom nav on content

- src/views/EmailLists.vue
> Fix alignment email lists

- src/components/AuthLogin.vue
- src/views/AuthLogin.vue
> Fix login color

- src/views/EmailListImportHelp.vue
- replace images
- minor style fixes
#117
> 117 fix import page contents

- src/components/PageNavigation.vue
- src/store/modules/auth.js
- src/store/modules/authKeep.js
- src/store/store-moderator.js
- src/views/AuthLogin.vue
- src/views/Home.vue
- src/views/Settings.vue
With this PR, we store user info in localstorage and read info from localstorage at first. Then we run a ping request to update user info on page load.  
So this way we have a cache layer for user info.  
#84
> 84 auth - fix login form blinking

- package.json
- yarn.lock
Upgrade tailwind to v1.4 https://github.com/tailwindcss/tailwindcss/releases/tag/v1.4.0
> upgrade tailwind to 1.4

- src/views/EmailListImportHelp.vue
> update csv template

- src/components/MemoListItem.vue
- src/views/MemoAdd.vue
> hotfix memos api requests/response

- src/components/BaseAppBarHeader.vue
- src/views/EmailListItem.vue
> Fix longer text on appBar component

- src/components/BaseProgressBar.vue
> Fix animation progress bar

- src/components/AuthLogin.vue
- src/components/MemoAddStep1.vue
- src/components/PostAddStep2.vue
- src/views/EmailListImport.vue
> fix move error messages inline

- src/components/BaseDropdown.vue
- src/components/Email/SelectEmailDate.vue
This issue [#30](https://github.com/whynotearth/Volkswagen-email-corperate-communications/issues/30)
> fix dropdown component

- src/components/Email/SelectRecipents.vue
- src/styles/plugin-multiselect.css
> Fix ui select recipient component

- src/components/PostAddStep2.vue
- src/components/PostAddStep3.vue
- disable image uploader
- hide image in preview post
> staging to master (hide image uploader, hide image in preview post)

- src/components/BaseDropdown.vue
- src/components/Email/DraftEmail.vue
- src/components/Email/ScheduleEmail.vue
- src/components/Email/SelectEmailDate.vue
- src/store/modules/email.js
> Staging to master

- src/components/ArticleAddStep1.vue
- src/components/ArticleAddStep3.vue
- src/components/Email/DraftEmail.vue
- src/components/PageNavigation.vue
- src/store/modules/email.js
- src/views/ArticleAdd.vue
- src/views/Email.vue
- yarn.lock
> Compatible ui new restructure

- src/components/Email/SelectEmailDate.vue
> refactor code for DraftEmail component

- src/components/Email/ScheduleEmail.vue
> remove limited for answers at a glance from step 3

- src/components/Email/SelectEmailDate.vue
> fix duplicate id in jumpstart preview page

- src/components/ArticleAddStep1.vue
> hide community article temporarily

- src/views/ArticleLists.vue
- src/views/ArticleListsItem.vue
- src/views/JumpStartLists.vue
> use fixed header in jumpstart-lists and article-list/item

- src/views/BlueDeltaSettings.vue
Wrong the link address.
This issue #218
> 218 fix link of here on blue delta settings

- src/views/ActivityFeedMemoList.vue
> #222 fix back link on the memo stats

- src/views/JumpStartLists.vue
This issue #174 
Add bottom navigation to the blue data page
> 174 add admins jumpstart

- src/components/JumpStartListItem.vue
Fix min height of item
This issue #174
> #174 fix min height of jumpStartListsItem

- src/components/BaseAppBarHeader.vue
- src/components/JumpStartListItem.vue
- src/views/JumpStartLists.vue
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/issues/230
> Jumpstart desktop style

- src/components/BaseChip.vue
- src/components/LayoutFixedScrollable.vue
- src/components/MemoListItem.vue
- src/components/MemoListItemOld.vue
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/issues/144
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/issues/145
> Memo list item new style

- src/router/index.js
- src/store/modules/auth.js
> fix auth issue

- src/components/Email/DraftEmail.vue
- src/components/Email/SelectEmailDate.vue
- src/components/JumpStartListItem.vue
- src/components/TodayEmail.vue
- src/store/modules/article.js
- src/store/modules/email.js
- src/views/ArticleLists.vue
- src/views/ArticleListsItem.vue
- src/views/BlueDeltaRearrange.vue
- src/views/EditBlueDelta.vue
- src/views/Email.vue
- src/views/JumpStartLists.vue
- yarn.lock
This issue #238 
Changes:
1. api/v0/volkswagen/articles/dailyplan is removed use api/v0/volkswagen/jumpstart/dailyplan instead
2. For JumpStart preview use api/v0/volkswagen/jumpstart/{date}/preview?articleIds= instead of
api/v0/volkswagen/jumpstart/{jumpStartId}/preview?articleIds=
3. To edit or create a JumpStart use POST api/v0/volkswagen/jumpstart
4. api/v0/volkswagen/jumpstart/{jumpStartId}/availablearticles is removed
--------------
fixing position of article in rearrange (It was better to remove the availablearticles so that this part would change sooner, It still needs to get better)
> 238 refactore api

- src/components/ArticleAddStep3.vue
- src/components/BaseDropdown.vue
> 252 refactor add article step3

- src/views/BlueDeltaRearrange.vue
- src/views/EditBlueDelta.vue
- src/views/Email.vue
- yarn.lock
> #264 change api for create & edit jumpstart

- src/views/ArticleListsItem.vue
> #220 add image uploader to Edit Articles

- src/router/index.js
- src/views/ArticleLists.vue
- src/views/BlueDeltaRearrange.vue
- src/views/EditBlueDelta.vue
- src/views/JumpStartLists.vue
> #280 refactor article lists & add blue delta

- src/components/BaseCounter.vue
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/issues/277
> negative counter problem fixed

- src/components/ArticleListsItem.vue
#247 
- changed title and tag, contents for desktop case in article page
> changed articles into mobile and desktop responsiveness

- src/components/ArticleAddStep2.vue
- src/components/ArticleAddStep3.vue
- src/components/ImageUpload/ImageUpload.vue
- src/store/modules/article.js
> image upload - add height/width to image model

- src/components/ArticleAddStep2.vue
- src/components/ImageUpload/ImageUpload.vue
- src/views/ArticleAdd.vue
- src/views/ArticleListsItem.vue
- Fix image uploader in article add/edit
- Fix article add/edit when there is no image selected
> image upload - fix image model in article edit/add

- src/components/ArticleAddStep2.vue
- src/store/modules/article.js
- src/views/ArticleAdd.vue
- src/views/ArticleListsItem.vue
- yarn.lock
> #290 remove price field from article

- src/store/modules/recipient.js
- src/views/ArticleListsItem.vue
> 304 change api of distribution groups

- src/components/ArticleAddStep2.vue
- src/components/BaseInputText.vue
- src/components/BaseInputTextarea.vue
- src/components/Editor/BaseEditor.vue
- src/views/ArticleListsItem.vue
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/issues/287
> Character counter

- src/App.vue
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/issues/291
> app load welcome message added to app.vue

- src/components/BaseTimePicker.vue
- src/views/EditBlueDelta.vue
Reverts whynotearth/Volkswagen-email-corporate-communications-CMS#285
This cause errors in blue delta edit. The implementation of set default value and emit data on input is wrong.
> Revert "261 fix default schadule"

- src/components/MemoAddStep1.vue
> #274 add vuelidate for multiselect in add memo

- src/views/BlueDeltaRearrange.vue
- src/views/BlueDeltaSettings.vue
- src/views/EditBlueDelta.vue
- src/views/EmailList.vue
- src/views/EmailListAdd.vue
- src/views/EmailListEdit.vue
- src/views/EmailListImport.vue
- src/views/EmailListImportHelp.vue
- src/views/EmailListItem.vue
- src/views/EmailLists.vue
- src/views/MyAccount.vue
- src/views/Settings.vue
> #272 fix headers for remain pages

- src/components/BaseChip.vue
- src/components/MemoListItem.vue
#263 
- added desktop sizing for memo stat
> added desktop sizing for memo stat

- src/components/AuthLogin.vue
Reverts whynotearth/Volkswagen-email-corporate-communications-CMS#316
> Revert "#307 add enter keyup event for login component"

- src/views/EditBlueDelta.vue
> #318 display error message to user in the edit blue delta page

- src/connection/ajax.js
> 211 fix 401 preview email

- src/components/TodayEmail.vue
> #289 fix dashboard button reroute

- src/components/BaseTimePicker.vue
> #324 fix color of timepicker

- src/components/Editor/BaseEditor.vue
Editor console error
https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/issues/332
> editor console error fixed

- src/components/ImageUpload/ImageUpload.vue
#335 Image deletion bug on Article Update page solved
> article image upload preview image deletion bug solved

- src/components/ArticleAddStep1.vue
- src/components/ArticleAddStep2.vue
- src/components/ArticleAddStep3.vue
- src/components/BaseNavigationBottom.vue
- src/components/Editor/BaseEditor.vue
- src/components/TodayEmail.vue
- src/router/index.js
- src/views/ArticleAdd.vue
- src/views/ArticleCategorySelection.vue
- src/views/ArticleListsItem.vue
Article category selection page created accoring to issue #182 and this PR is alson related to #242 
New Article buttons direction changed to route named ArticleCategorySelection.
> Article category selection

- src/components/ArticleAddStep2.vue
- src/components/Editor/BaseEditor.vue
- src/views/ArticleListsItem.vue
ArticleAddStep2.vue editted according to issue #287 and #176 
Excerpt field changed to editor and live character counter editted according to vuetify's version
> 176 287 editor and live character counter

- src/views/ArticleListsItem.vue
#340 
refreshing edit article page causes error because of lack of daily plan after refreshing.
To make it work I fetched daily plan if there is no daily plan at Vuex store.
> update refresh article edit page bug solved

- src/components/BaseNavigationBottom.vue
- src/router/index.js
- src/views/ArticleAdd.vue
- src/views/ArticleLists.vue
- src/views/ArticleMain.vue
#344 
- created new article creating page
- linked all necessary route to article related pages
- matched all page components into design
> complete Article pages and link some necessary pages

- src/components/BaseNavigationBottom.vue
- src/providers/JumpStartProvider.vue
- src/router/index.js
- src/views/BlueDeltaMain.vue
- src/views/JumpStartLists.vue
#352 
- created BlueDeltaMain page
- created two buttons
- integrated header nav bar
- integrated bottom nav bar
> complete Blue Deta Jump Page

- postcss.config.js
Reverts whynotearth/Volkswagen-email-corporate-communications-CMS#233  
Julia reported there is a lot of bugs, so I revert it.
> Revert "fix: purgecss"

- src/components/AuthLogin.vue
- src/components/BaseAppBarHeader.vue
- src/components/BaseButton.vue
- src/components/BaseInputText.vue
- src/router/index.js
- src/views/AuthForgotPassword.vue
- src/views/AuthNewPassword.vue
- src/views/MyAccount.vue
- Prevent show error on focus and unfocus with empty data on all input texts
- Prevent double submit in login #374 
- Prevent error in inputText when value is null
- Fix some input error margins in reset password
- Fix redirect to dashboard after reset password
- Add error message when url is not valid in new-password page
- Fix validation in reset password form
> minor bug fixes in auth pages and input texts

- src/components/BaseAppBarHeader.vue
- src/components/LayoutFixedFooter.vue
- src/components/LayoutFixedScrollable.vue
- src/components/StepperHeader.vue
- src/components/StepperManager.vue
- src/views/MemoAdd.vue
- In PR #369 changes caused a bug for fixed header and footers in layouts, This PR is a bugfix for it. #368
- Fix z-index of header and footer. Now the order of layers should be correct.
> fix header to top in different layouts

- src/providers/ActivityFeedDetail.vue
- src/views/ActivityFeedMemoItem.vue
Fix a critical error in stats pages
#386
> fix transition error in layout for group elements

- src/components/StatsOverview.vue
- src/views/StatsOverviewJumpstarts.vue
- src/views/StatsOverviewMemos.vue
#378 
Provide steps on how one can test your changes here. e.g.
1. Go to stats page
2. Go to jumpstart stats
- User activity chart not included
- API not connected yet
> 378 add jumpstart stats overview

- src/components/BaseAppBarHeader.vue
> appbar - fix text cuttoff

- src/store/modules/email.js
#398 
Could not reproduce it but it should be fixed now.
> fix todayEmail console error

- src/components/MemoAddStep2.vue
> memo preview - fix chattanooga logo size in desktop

- src/store/store-moderator.js
> clear article form storage on logout

- src/components/LayoutFixedFooter.vue
> fix double scroll

- src/components/BaseNavigationBottom.vue
- src/components/TodayEmail.vue
- src/providers/JumpStartList.vue
- src/router/index.js
- src/views/BlueDeltaMain.vue
- src/views/BlueDeltaRearrange.vue
- src/views/BlueDeltaSettings.vue
- src/views/JumpStartLists.vue
- src/views/Settings.vue
- src/views/Stats.vue
#417
I just renamed it everywhere in UI (even on urls) but not in main welcome text: "Welcome to Blue Delta" because I thought it's the project name. Let me know if I should rename it too.  
Also file names, component names and route names are not changed.
> rename blue-delta to jumpstart

- src/components/ChartTagUsage.vue
- src/store/modules/email.js
- src/store/modules/memo.js
- src/views/StatsOverviewJumpstarts.vue
- src/views/StatsOverviewMemos.vue
#400 
fix date range selector and connect tag usage chart to api
pages updated: memo stats overview, jumpstart stats overview
> 400 stats overview connect api

- package.json
- src/helpers.js
- src/store/modules/distributionGroup.js
- src/views/StatsOverviewDistributionGroup.vue
- yarn.lock
#411 
_For New Features:_ This is a continue for PR https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/pull/424
In this PR I've connected vuex store to api and and added export report functionality. However reports are empty right now and we should add some data to see lines on charts.
Provide steps on how one can test your changes here. e.g.
1. Go to settings => distribution groups
Delete list buton's functionality not included in this PR
> 411 stats overview distribution groups - connect to API and add export report functionality

- src/helpers.js
- src/store/modules/distributionGroup.js
- src/store/modules/email.js
- src/store/modules/memo.js
- src/views/StatsOverviewDistributionGroup.vue
- src/views/StatsOverviewJumpstarts.vue
- src/views/StatsOverviewMemos.vue
Put the issue(s) # that your PR is addressing here. e.g. #15, #29
#400 
_For New Features:_ Add export report functionality
1. Go to one of stats overview pages
2. Click Export Report
Individual Jumpstart Stats not included. #413
> overview stats [memos/jumpstarts/dist groups] - add export functionality

- src/components/BaseNavigationBottom.vue
#430
_For Bug Fixes: hide article link from bottom navigation
> 430 hide article

- src/bridges/StatToActivity.js
- src/providers/ActivityList.vue
- src/providers/ActivityListItem.vue
- src/providers/JumpStartDetail.vue
- src/store/modules/email.js
#432 
_For Bug Fixes:_ 
1. Go to `/stats/memos/activity` and `/stats/memos/activity/69`
2. See if description text is looking fine (I just increased the height of text that was cutoff)
also for jumpstarts
> 432 fix memo/jumpstart stat activity item preview text

- src/components/ChartTagUsage.vue
- src/components/ChartsStatsOverview.vue
- src/views/StatsOverviewJumpstarts.vue
#434 
_For Bug Fixes:_ chart border left color, fix vertical lines outside of chart area, fix spacing
> stats overview charts - fix styles

- src/components/ChartTagUsage.vue
#441 
_For Feature Updates:_ I could only toggle other lines by click on labels for now. Doing the complete requested behavior takes more time.
> stats overview tag usage - update legend click behavior

- src/views/BlueDeltaSettings.vue
#433 
_For Bug Fixes: I tested all project for multiselect & dropdown, dropdowns are okay but multiselect have bugs
I attached screenshots to #433 
/settings/jumpstart
> #433 fix multiselect on buledelta settings page

- src/router/index.js
> disable jumpstart direct url links

- src/components/BaseNavigationBottom.vue
- src/router/index.js
- src/views/BlueDeltaSettings.vue
- src/views/Settings.vue
- src/views/Stats.vue
Enable references to jumpstart and stats
> Enable jumpstart and stats
